# Generated by Django 4.0.5 on 2022-07-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_playlistelement_options_alter_playlist_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlistelement',
            unique_together=set(),
        ),
    ]
