# Generated by Django 4.0.5 on 2022-07-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_playlistelement_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medialink",
            old_name="url",
            new_name="source",
        ),
    ]
