# Generated by Django 4.0.5 on 2022-07-07 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_rename_url_medialink_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlistelement",
            name="media_link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to="main.medialink",
            ),
        ),
    ]
